### ISSUE TITLE
Keyword argument error

### ISSUE THREAD

**Issue by crichardson332** [josejg/instruction_following_eval#2]
The following test results in an "unexpected keyword" error:

```
from datasets import load_dataset
from instruction_following_eval import get_examples, evaluate_instruction_following

dataset = load_dataset("google/IFEval")

data = [dataset['train'][0]]
metrics = evaluate_instruction_following(data, ["response text goes here"])
```

Output:
```
Traceback (most recent call last):
  File "/home/heck2/crichardson8/gitrepos/ava-nlf/ifeval_test.py", line 7, in <module>
    metrics = evaluate_instruction_following(data, ["response text goes here"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heck2/crichardson8/gitrepos/instruction_following_eval/instruction_following_eval/evaluation.py", line 103, in evaluate_instruction_following
    strict_results = [test_instruction_following(ex, resp, strict=True) for ex, resp in zip(input_examples, responses)]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heck2/crichardson8/gitrepos/instruction_following_eval/instruction_following_eval/evaluation.py", line 103, in <listcomp>
    strict_results = [test_instruction_following(ex, resp, strict=True) for ex, resp in zip(input_examples, responses)]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/heck2/crichardson8/gitrepos/instruction_following_eval/instruction_following_eval/evaluation.py", line 82, in test_instruction_following
    instruction.build_description(**example.kwargs[index])
TypeError: CommaChecker.build_description() got an unexpected keyword argument 'num_highlights'
```

**Comment by crichardson332** [comment]
The problem seems to be solved by adding `**kwargs` to the argument list for the `build_description()` methods in the subclasses of `Instruction`, e.g.
```
class CommaChecker(Instruction):
    """Checks the response for no commas."""

    def build_description(self, **kwargs):
        """Build the instruction description."""
        self._description_pattern = (
            "In your entire response, refrain from the use of any commas."
        )
        return self._description_pattern
```
but this would need to be added to every method. Is there a better fix?
